### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by f1est0** [Roeshambo/MonolithDKP#108]
Date: 2019-11-22 13:45:30
ID: 1
Error occured in: AddOn: MonolithDKP
Count: 1
Message: Note: AddOn MonolithDKP attempted to call a protected function (CompactRaidFrame36:ClearAllPoints()) during combat lockdown.
Debug:
   [C]: ClearAllPoints()
   ..\FrameXML\FlowContainer.lua:157: FlowContainer_DoLayout()
   ..\FrameXML\FlowContainer.lua:17: FlowContainer_ResumeUpdates()
   ...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185: CompactRaidFrameContainer_LayoutFrames()
   ...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: CompactRaidFrameContainer_TryUpdate()
   ...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:62: CompactRaidFrameContainer_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:

**Comment by Roeshambo** [comment]
This is an error on the part of Blizzard unfortunately. I'm not certain there's any way to avoid it. It's an issue with taint caused by (from what I believe) the use of dropdown menus. For whatever reason, they decided it's a taint that should spider into other elements such as default raid frames. It has also apparently been an issue plaguing addon developers for the better part of a decade. So i don't imagine anything changing. If I can find a way to correct it, a fix will be added.
