### ISSUE TITLE
LUA Error 1.6.3 every DKP update

### ISSUE THREAD

**Issue by bjordan2010** [Roeshambo/MonolithDKP#121]
Getting a LUA error in 1.6.3 in classic every DKP update.  The officer would update DKP and everyone would get this error.

![Screen Shot 2019-11-27 at 12 59 44 AM](https://user-images.githubusercontent.com/704324/69700917-4e788b00-10b1-11ea-8d55-6cae9c82437d.png)

Looks like some variable in a comparison on my line 95 is nil and isn't expected to be.  Not sure if it's role or rankName though.   Appears to be line 101 in master.  Is it something the we are suppose to set and haven't or a code issue?

**Comment by Roeshambo** [comment]
It appears as though someone in your profile table has a nil value for either rankName or role. I'm betting role, since rank is checked against the guild and applied quite frequently. Every function that can add a player to the table adds a placeholder "No Role Reported" until it gets changed by receiving their spec information. That section shouldn't even be firing unless they had typed something into the search window. I'd go through your MonDKP_DKPTable if it's not terribly huge, and find which profile doesn't have a ["role"] field. As to how that would have happened, I've no clue. It's simply not possible to create a profile without including that field.

**Comment by Roeshambo** [comment]
Only thing I can think of that would cause that is one of the officers accidentally deleted the field while looking through it and then broadcasted it?

**Comment by bjordan2010** [comment]
I browsed through my MonDKP_DKPTable and all of the entries have a role and a rankName.  Could this be in the officer's MonDKP_DKPTable who was sending the broadcast?

One last thing, the table ends with ["seed"] = <aNumber>,
where <aNumber> is a long whole number.  This seed kv pair is not surrounded by brackets and has a comma at the end like it should have another kv pair.  However, all objects in the .lua file seems to do this so the seed thing may not be a problem, just looks strange.

**Comment by bjordan2010** [comment]
I think we found the problem, going to test later when everyone is on.  The officer had people in DKP who had left the guild.  My guess is that it could not populate their rankName since they were no longer in the guild.  I'll close this if our test of the next broadcast doesn't cause the error.

**Comment by Roeshambo** [comment]
Ah, then that would be a bug with the script as it's supposed to just say "Not in Guild" if they aren't found. Although I would still be clueless as to how it would have happened. I'm currently using a SV file with 250 players in it, none of whom are in my guild, to stress test the new system. And have never had an issue with it.

**Comment by Roeshambo** [comment]
Added redundancy to make sure the rank/rankName fields are not tampered with.
