### ISSUE TITLE
Added Functionality

### ISSUE THREAD

**Issue by Balazar1516** [Roeshambo/MonolithDKP#13]
Would it be possible to add functionality for either a zero sum system or a fixed cost system? Adding in an option for a max bid and then allowing the bid list to be sorted by total DKP rather than bid amount could work.

**Comment by Roeshambo** [comment]
Max bid will be in the next version. Zero sum was something I thought about adding. But it's incredibly unlikely anyone would use it since it's one of the least popular methods. So i passed it over in favor of adding more in-demand features.

**Comment by kickit9** [comment]
I really enjoy your addon, well done! My guild will be using a dkp/roll system. Individuals will do a /roll out of 500 (this number can be adjusted) and then add their DKP to the roll so that you end up with a total that is the sum of your roll + your DKP. I have used this system since Vanilla it is simple but effective. It would be amazing if you could integrate a feature for something like this. Thank you for your time!

**Comment by Roeshambo** [comment]
I will be adding a roll system, hopefully by the weekend, along with other DKP methods.
