### ISSUE TITLE
Sync never completing - missing entries

### ISSUE THREAD

**Issue by JGITE** [Roeshambo/MonolithDKP#174]
Hey,

First of all, amazing addon.  You've saved me so many hours of hard manual work I don't even know where to begin.

The issue I'm having is that post upgrade, my sync never seems to complete.  I am the GM (Gaskie), and the one who performed the migration.  Everything appears to be working fine, we did a full raid last night with the new version and everything looks correct, loot was tracked correctly and everyone seems to have the correct DKP.

That said, on the sync button is tells me I have 13 missing entries, and this never seems to resolve, meaning the button stays  yellow and doesn't go green as I'd expect it to.

I'd really like to resolve it in case it causes me further issues down the line.  Any and all help greatly appreciated, and thanks once again for your hard work.

[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3939604/MonolithDKP.lua.txt)

**Comment by JGITE** [comment]
Sorry - just to say that the renamed .txt file in the original message is my pre-migrated file.  I've attached the post migration file to this message (as a zip) which will include last night's raid, for comparison.


[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3939616/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
I see your issue. As soon as I get home I'll get that migrated properly for you.

**Comment by Roeshambo** [comment]
I'm assuming Gaskie is the migrating officer. So I'll be migrating it in their name. Is this correct?

**Comment by Roeshambo** [comment]
Here is a properly migrated copy migrated in the name of Gaskie (that was who migrated your first file there). Most important part, ensure ALL officers wipe their tables (button to do so in the options tab). Then close your game, throw this SV file into your folder and log in with it. Do not log in with it until all officers have wiped their data or else it will get corrupted when they start sending you stuff. Your "Missing Entries" may be a bit off at first if non-officers have the incorrect data but it should fix itself over time. If you have all of them wipe their data that will help prevent this. That would be caused by other players thinking more entries exist than actually do (from the previous migration).
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3941120/MonolithDKP.zip)

**Comment by JGITE** [comment]
This is great, thank you.  My only issue now is that last night's raid (which I ran on my alt, Cptinsano) is missing, which includes both the DKP award and the loot history.  Any easy way for me to fix this?  I'm keen not to waste any more of your time as you clearly have a lot going on.

This raid can be seen in the second file I uploaded

**Comment by Roeshambo** [comment]
I'll look at it as soon as I get home and merge them as needed

**Comment by Roeshambo** [comment]
This is the table i sent you with incorporated 24 Loot entries and 1 DKP entry created by "Cptinsano"
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3942194/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
If you have any additional issues after that, please comment and I'll reopen :)
