### ISSUE TITLE
Guild Master out of Sync with himself

### ISSUE THREAD

**Issue by Zelden848** [Roeshambo/MonolithDKP#176]
As stated in a comment on the Addon page, since updating to 2.01 and migrating the data an issue arose on the next login where I became out of sync with myself.

Wiping the table did not resolve the issue and as time goes on I am out of sync with an increasing number of entries.

Attached saved variables.
[Variables.zip](https://github.com/Roeshambo/MonolithDKP/files/3940702/Variables.zip)

**Comment by Roeshambo** [comment]
Were you the officer that conducted the migration?

**Comment by Zelden848** [comment]
Yes

**Comment by Roeshambo** [comment]
Do you have a copy of the saved variables before migration? It appears that this one you posted only has 22 loot entries.

**Comment by Zelden848** [comment]
I can't seem to find my backups. When I migrated it said it was successful. Orb was Green and then did a raid that night and handed out DKP. Next day when I logged in it was out of sync with myself.

It's not a huge deal if it can't be reconciled, I just want to clear the error and ensure there's no chance of it suddenly resyncing and messing up.

**Comment by Roeshambo** [comment]
Did you initially only have 22 loot entries in it? Or was it far greater?

**Comment by Roeshambo** [comment]
Your file looks all correct with one exception. The MonDKP_Meta_Remote table says you have 288 loot entries and 394 DKP entries. That table stores what other people think you have. So that means someone in the guild thinks you have far more entries than you actually do. With the new version i pushed recently it *should* automatically reconcile it as if anyone thinks you have more than you actually do, you tell them to fix it automatically during a sync. Since it would obviously be wrong. You may want others to simply wipe their tables and redownload the data from you.

**Comment by Zelden848** [comment]
Awesome, will see how it goes and report back if there are more issues.
