### ISSUE TITLE
We had a raid with the new version without migrating, can I start the migrate process now?

### ISSUE THREAD

**Issue by Artina457** [Roeshambo/MonolithDKP#177]
Hey, 
we initialized a raid killed ony, Distributed some loot, but now I have the only updated Version of the DKP. While others have e.g. 20 DKP from the raid today.

Can I somehow start the migrate now? or fix this?

**Comment by Roeshambo** [comment]
Yes if you migrate and they install 2.0.5 you'll distribute the new information to them. If I'm reading that right. You have all of the current data correct?

**Comment by Artina457** [comment]
Yes thats right. But /DKP Migrate doesent seem to work

**Comment by Roeshambo** [comment]
You have 2.0.5? Make sure guild leaders note is empty (doesn't say {MonDKP=OfficerName}) and then type /dkp migrate (lower case). It'll only come up if you have 2.0.5 installed. Make sure you are the ONLY officer that migrates.

**Comment by Artina457** [comment]
Going to try it now. We did one ony raid With 2.03 on me, and some other players in the raid had updated as well, without completing the migration first. Should i be receiving a reply in chat when typing /dkp migrate ?

**Comment by Roeshambo** [comment]
A box would pop up with instructions and a button to migrate.

**Comment by Roeshambo** [comment]
If it's not, please post your saved variables file and I'll get it fixed for you

**Comment by Artina457** [comment]
[MonolithDKP.txt](https://github.com/Roeshambo/MonolithDKP/files/3941300/MonolithDKP.txt)
[MonolithDKP_Bidhook.lua.txt](https://github.com/Roeshambo/Mono
[MonolithDKP.lua.bak.txt](https://github.com/Roeshambo/MonolithDKP/files/3941303/MonolithDKP.lua.bak.txt)
lithDKP/files/3941302/MonolithDKP_Bidhook.lua.txt)

**Comment by Artina457** [comment]
It doesent show up when i type /migrate so I sent the files

**Comment by Roeshambo** [comment]
Ok I'll get that migrated for you as soon as I get home. Make sure no other officers have migrated. If they did, have them wipe their tables

**Comment by Artina457** [comment]
kk, thank you! legend

**Comment by Roeshambo** [comment]
This is the migrated file. Ensure ALL of your officers wipe their tables, first and foremost, before logging in with this. All other players should wipe their tables as well (button in options tab), but the most important part is the officers wipe because they are the ones that can broadcast bad data back to you if they still have old information. After they have wiped their tables, close your client and load this into your SavedVariables file and log in. Shortly after, you will begin broadcasting these to everyone that has empty tables. It has been migrated as the name "Artina". If "Artina" is not an officer, it could cause some issues. Let me know if that's the case. And if this doesn't resolve your issue please comment and I'll reopen :)
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3942216/MonolithDKP.zip)
