### ISSUE TITLE
2.0.5 problem with Sync and Broadcast

### ISSUE THREAD

**Issue by dr4i3n** [Roeshambo/MonolithDKP#186]
Hello i have problem with Sync and Broadcast DKP. I see every DKP correct but cant broadcast or sync to guild members. My Version is 2.0.5

Thx for any help.

[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3946507/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
It seems your file wasn't indexed properly when migrated. Likely a residual issue from the earlier release of 2.0. As soon as I get home I'll reindex it for you. Is "Earthshaker" the proper officer to index it as?

**Comment by dr4i3n** [comment]
yeah Earthshaker is Guild Master. but my officer tried migrate and now he is see DKP correctly

**Comment by Roeshambo** [comment]
Ok. If he did it and it's correct, all officers must just wipe their tables (button in Options tab) so he can send them to you.

**Comment by dr4i3n** [comment]
now i see all DKP doubled.

**Comment by dr4i3n** [comment]
wiped tables and now its seems OK.

**Comment by Roeshambo** [comment]
Ya since your tables weren't wiped and you had indexes already it probably duplicated your history unfortunately. I'll get it fixed up for ya. Just have all of your officers wipe their tables and I'll get this file migrated for you as soon as I can. Then after your officers are wiped and have no information in their tables, you can load up with the new one and it'll broadcast to them. Any non officers in your guild will also need to wipe. Hopefully you didn't send him your indexed entries. Cuz it might get all screwy.

**Comment by Roeshambo** [comment]
If you see 3 loot entries and 1 DKP entry in the history created by you, Loot: Helm of Wrath, Head of Onyxia, and Sapphiron Drape, and DKP: Onyxia's Lair: Onyxia. Check to see if they're duplicates. If they are, just right click and delete the ones by you and you should be all set.

**Comment by dr4i3n** [comment]
i think now its everything corrent. thanks for help. wipes helped

**Comment by Roeshambo** [comment]
No problem.
