### ISSUE TITLE
Migration issues

### ISSUE THREAD

**Issue by alatterner** [Roeshambo/MonolithDKP#198]
Sorry for clogging up your issue tracker. 

We're starting to notice some weirdness after migration. Some folks have entries that are no longer visible or in the file, however the number on my table reflects their actual DKP correctly.

For instance, we have one person who earned 18 DKP 2 weeks ago. For some reason, that entry as to why they earned it isn't there. However, I still see them with 18 DKP. It's nothing that terribly serious as losing the reason isn't important to me.

However, when other officers are comparing their values to me after the migration, they don't see that original value of 18. They have an original value of 0 (after they deleted their tables and resynced). Given that there is no history of this interaction, it appears that it didn't properly get updated for them.

I was looking through the file itself trying to figure out where the "initial value" might be stored for me and how I might be able to replace those values with a value of 0 and programatically add new values to create that history, however cannot figure out where that lives in the file itself.

Attached are my saved files. The specific case for an example (though a few cases of this exist) would be "Brokenwind". He has one entry in there for decay (that was properly calculated assuming he had 18 dkp) and one entry for his character information. However, no entry for how he got that initial 18 dkp. Just trying to figure out where that's stored/calculated
[saved_values.zip](https://github.com/Roeshambo/MonolithDKP/files/3948822/saved_values.zip)
.

Thank you so much for all of your help!!!

**Comment by Roeshambo** [comment]
It's actually probably very simple. The reason i wrote this new broadcast system was because the old system was kinda... iffy at best. It broadcasted entire tables. Which took time. (could take up to 30-45 seconds if the table is large enough). Problem with that is, if you edit another entry, create a new entry, or anything like that, you'd start a new broadcast. Which would essentially overwrite the first broadcast that was still in progress. It resulted in history entries being completely lost. This is very likely what happened here. However, you'll notice an entry in there with a "reason" of "Migration Correction". I basically assumed the DKP table would have the correct values and the history would be the most likely table that would be wrong. So during the migration, it combines both loot and DKP history tables chronologically and then adds everything up for each player. Then it creates that new entry compensating for the difference between what the DKPTable says their DKP is and what the history actually added up to. You appear to have all of your indexes and no entries have been removed, at least since the migration. Hopefully that all makes sense in text.

**Comment by alatterner** [comment]
That's very helpful. In terms of what everyone else sees, what would be the best way to fix that? 

Currently, one of my other loot masters for another raid is trying to update to my tables (wiping tables and resyncing) and they still see some of these entries without the original value. It appears that the migration correction fixed most of them, however not all of them. Brokenwind, for example, was someone who received DKP for donating to the guild bank (entry under "Other - Requisition"), however, for some reason that no longer exists (which makes sense given what you said about the old system).

So originally, they had 18 DKP from this requisition (other dkp award, non raid related. Also got lost to time).
They then have a 10% weekly decay this week (subtract 2)
So their final DKP should be (and in my tables is) 16.

However, for the other officers, they don't have that original value of 18 DKP. They only have the subtract 2 that I did, resulting in a DKP of -2. This occurs even after repeated wiping of their tables and resyncing.

Looking at the migration correction, it appears to not have taken Brokenwind's old DKP into account. However, in my log, it still shows him as having DKP. Does this make sense?

**Comment by Roeshambo** [comment]
Yes i see what you're saying. I'm not sure why it would have left him out of that Here's what I would do. Take a snapshot of everyone's current DKP (the table on the left) if all of those values are correct. Then you'll right click on that table and there will be an option to "Validate Tables". This takes a few minutes to run but what it does is it combs through everyone's history and rebuilds their profile based off of that history. So if the history, for say Brokenwind, does in fact add up to -2, it's going to change his DKP to -2. Then you'll compare your screenshot of the correct DKP, and simply adjust their DKP to be correct in the Adjust DKP tab. So if he's supposed to be at 16 and it's at -2 after the validation, just give him 18 DKP. This will create those new entries that everyone else will receive and then they should have the correct DKP.

**Comment by Roeshambo** [comment]
I'll run that validation on your table really quick just to make sure nothing was missed.

**Comment by Roeshambo** [comment]
Another thing you can do to make it easier to do. Before you do the validation, right click and "Select All" then right click again and click "Reset Previous". This will set that number on the far right in parenthesis to 0. That number simply tells you how much their DKP has changed since the last time you reset it. Then run the validation and when it's finished, those numbers will tell you how much each persons DKP changed.

**Comment by Roeshambo** [comment]
Ok so here's your table before the validation:
![image](https://user-images.githubusercontent.com/6285297/70600547-8dc8d080-1bb5-11ea-810e-4ae2485bf5d5.png)

And here's your table after the validation:
![image](https://user-images.githubusercontent.com/6285297/70600583-a9cc7200-1bb5-11ea-963e-b5cb0c00a068.png)

**Comment by Roeshambo** [comment]
It looks like Brokenwind's history is off by 18 and Cheeriojoe is off by 1. There's like 5 or 6 others slightly off but most were accurate.

**Comment by alatterner** [comment]
Perfect. I did the same rough merge in google sheets and was able to find the list of modifications I need to make there as well. Thank you so much for your help with this.

Let me know if you want me to close this ticket or keep it open for your records if you need to adjust anything.

**Comment by Roeshambo** [comment]
Nope it can be closed unless you need assistance with anything else.
