### ISSUE TITLE
Migration from 1.6.3 to 2.0.5 issue

### ISSUE THREAD

**Issue by reave-anathema** [Roeshambo/MonolithDKP#199]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3949076/MonolithDKP.zip)

Hi, can you please help? We seemed to have had an issue during migration. My tables look good, but the officer who initially migrated now has a blank screen and it tells him no officers are online to sync. Attached is my current post-migration lua file (sorry I don't think I have the pre-migration file).

Please help.

**Comment by Roeshambo** [comment]
Of course. There are two things that can cause it to say no officer is online (I believe i actually updated that verbiage in the newest version, but perhaps I overlooked that). Either no officers respond because they aren't online, or because no officers responded to a sync request because they were on cooldown. There's a 60 second cooldown between sync requests to help reduce spam. I'll take a look.

**Comment by Roeshambo** [comment]
Your file looks fine. You just appear to be missing one Loot entry (Swindler-1). You would be able to get it from him when he's online. (Clicking the status button in the bottom left of the UI will either submit a sync request if a nonofficer, or begin a sync if you are an officer) If it tells him there are no officers online when there actually is one that has the current version of the addon, have him wait 30 seconds and request another sync.

**Comment by reave-anathema** [comment]
Swindler was on during the migration process and for hours afterwards, but it never updated for some reason. Eyesmcfly is the officer who performed the initial migration, but it's telling him no officers are online 100% of the time (even when I'm online, for example). And if Eyesmcfly waits for the sync CD, it then tells him no officers are online and doesn't give him an option to sync again. Is there something else we should try? Thanks for the quick replies!

**Comment by reave-anathema** [comment]
Scratch that! I think we're good now--thanks for looking into this:)

**Comment by Roeshambo** [comment]
No problem. Please comment on this if you find you need additional assistance.

**Comment by ghost** [comment]
Hi Roeshambo,

This issue hasn't actually been resolved. I'm the officer that initiated the migration. During migration one of our officers logged off because he realized he had the wrong version. That officer was Swindler, and since migration we have had the message "Missing Entries: Swindler: 1" ever since.

Some background context.

A bunch of our members auto upgraded through Twitch right before a raid, and to accommodate them the DKP officers decided to move forward with upgrading as well. So, unfortunately, we didn't plan this well.

We synced our 1.6 tables, and then I started migration. After I started migration Swindler logged off because he was on an older version, he logged back on again with the newest version before migration completed.

When migration completed my status orb turned red and showed an error saying something like checking for corrupted entry. After that everyone has had "Missing Entries: Swindler: 1" ever since, including Swindler himself.

Since migration my status orb has never shown green or up to date. I've tried a lot of different things to fix it, but I haven't had any luck. Here is a list of what I tried: reloading the UI, logging in/out, manually sync - this led to "no officers available" while Swindler and Reave were online with me. I uninstalled and reinstalled Monolith.

All of this troubleshooting ended with me having a blank DKP screen and getting "no officer available" when I tried to sync. When I couldn't make any progress there, I tried manually copying Reave's data file. This is when Reave though the issue was resolved. After copying his data file I could see all of the DKP entries, but my table still shows out of date, and still shows "Missing Entries: Swindler: 1".

At this point, I can see our correct DKP pre-migration, and I can see the correct DKP gained from our last raid, but I don't see any entries for DKP spent on loot from the last raid, and my status orb stays red and says I'm out of date.

**Comment by Roeshambo** [comment]
Can you post your sv file and we'll get you sorted out

**Comment by ghost** [comment]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3958323/MonolithDKP.zip)

This file came from Swindler. I tried uninstalling an reinstalling again, and my entries are blank, and i'm getting "no officer available" when I try to sync.

**Comment by Roeshambo** [comment]
No one has added any entries since that file correct? Last loot entry is from Majordomo and last DKP entry is from the same mob (plus 2 after that say AFK and BOSS AFK

**Comment by Roeshambo** [comment]
If so, here's the file. You shouldn't have to do anything special. Somehow one of Swindler's loot entries got removed. So I created a new loot entry and then another to delete it (basically just cancels it out but fills the gap without altering DKP)
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3958435/MonolithDKP.zip)

**Comment by ghost** [comment]
Okay thanks for taking a look at it. Can I share this file with all the DKP officers so that we're all on the same page. And if so, what do they need to do to copy it?

**Comment by Roeshambo** [comment]
You can if you like. They just need to put it in place of their file while their WoW client is completely closed.

**Comment by ghost** [comment]
thanks roeshambo, that has got things working, we're still having a few issues, but we're able to work through it. I appreciate the help!
