### ISSUE TITLE
dkp tables messed up again since last update

### ISSUE THREAD

**Issue by lykann1337** [Roeshambo/MonolithDKP#201]
hi there again

After updating to 2.0.6 I logged in to find all my tables changed so that people have near 5x what they had before the update! tried getting people to delete their tables and still it just updates to the one with 5x the actual amount of dkp and alot of peoples is even more than this from what I can tell!

please help I have a raid in 1 hour!
Thanks
Gambiit
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3951526/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
Are you an officer? And if so, your character name is Gambiit?

**Comment by lykann1337** [comment]
yes and yes, I held the master tables before it all went tits up

**Comment by Roeshambo** [comment]
Ok I'm going to remigrate and validate your table for you. When you have ALL officers online (anyone with permission to edit DKP), have them go to Options tab and wipe tables. They want to get rid of everything. Then you're going to log off and load the SV file I give you and it'll distribute to them. After you sync, it's probably going to say you have entries missing. That's normal and its because non officers in the guild still have old data. They will just need to wipe their tables the same way and request a sync. Officers is the most important though since they can broadcast entries and contaminate your tables.

**Comment by Roeshambo** [comment]
Or if you want to play it extra safe, you can simply have all officers log off jsut before the raid and give them this SV file to load. Then you won't have to wait for a sync.

**Comment by lykann1337** [comment]
might be best to go with the extra safe option tbf :D just to be sure ty!

**Comment by Roeshambo** [comment]
This look like correct DKP to you?
![image](https://user-images.githubusercontent.com/6285297/70645135-0194c880-1c0a-11ea-9259-9f548b85f95e.png)

**Comment by lykann1337** [comment]
no thats not the amount it was before I can send u the table of what it was so the below is what it should be
[MonolithDKP - Copy.zip](https://github.com/Roeshambo/MonolithDKP/files/3951770/MonolithDKP.-.Copy.zip)

**Comment by Roeshambo** [comment]
Ok one moment.

**Comment by Roeshambo** [comment]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3951790/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
Sorry uploaded wrong one for a moment there. Here you go.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3951794/MonolithDKP.zip)

**Comment by lykann1337** [comment]
okay appears to be sorted now! Once again thank you for the help! and swift response! Great job with the addon as always!

**Comment by Roeshambo** [comment]
If you have any more issues with that please post here and I'll readdress it.
