### ISSUE TITLE
DKP Table wipes with v2.0.0+

### ISSUE THREAD

**Issue by Cimpster** [Roeshambo/MonolithDKP#205]
Hi,

as discussed per dm, here are my saved variables to migrate.

[SavedVariables.zip](https://github.com/Roeshambo/MonolithDKP/files/3951896/SavedVariables.zip)

**Comment by Roeshambo** [comment]
Thank you. As soon as I get back home I'll get that remigrated for you and give you instructions to make sure it goes smoothly. In the mean time, I would have everyone in your guild wipe their tables to avoid complications from old data. Button in Options tab can do that. When I do migrate it, to be extra safe, you want to have all officers wipe their tables and after they've done that, you can give them the migrated file I give you. Client must be closed entirely to load it up.

**Comment by Roeshambo** [comment]
What is the officers name that the migration should be done as?

**Comment by Roeshambo** [comment]
Ok first and foremost you're going to want to make sure all of your officers delete their saved variables files. If they have permission to change DKP within the addon (Have "Edit Officer Notes" permissions within your guild settings), they need to delete their SV file (backing up prior to deleting wouldn't be a bad idea). Everyone else in the guild needs to wipe, but officers need to be 100% sure they do before you deploy this or they could broadcast bad data to you. Then once all officers have deleted their SV file (even the ones that are not whitelisted but have those edit officer notes settings) go ahead and load this file up into your savedvariables folder and give the same file to those officers and have them do so as well. This will ensure no one with broadcast permissions will have incorrect data. Everyone else in the guild will then get broadcasts when they wipe their tables (options tab). 

If you end up seeing a red status indicator and it says you're missing X number of your own entries, ignore that. It's because someone in the guild still had old data and think you should have more than you do. That should auto resolve itself when everyone gets on the correct data. This was migrated as "Cimp". If that is not correct let me know and I'll change it.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3953030/MonolithDKP.zip)

**Comment by Cimpster** [comment]
Everything is working now.
Thank you so much!:O
