### ISSUE TITLE
Missing Entries Reported

### ISSUE THREAD

**Issue by nomenclad** [Roeshambo/MonolithDKP#206]
I've had all officer with syncing power wipe tables to start fresh. When I sync with the guild I still get a message that I'm missing entries. Is this because members in the guild haven't wiped tables or is this limited to an issue with an Officer's addon?

![image](https://user-images.githubusercontent.com/58759698/70649525-53921a00-1c1b-11ea-9b99-d0c5426bf3e9.png)

**Comment by Roeshambo** [comment]
Post your saved variables file and I'll make sure. If you are "Pewed" then I can almost guarantee it's because a member somewhere has either old entries or an old Meta table and is telling you that more entries exist. In the newer versions I incorporated something that should correct it over time but only if both parties have that version or later (believe 2.0.5 when I added it?). Best way to figure out who that is would be to close your game and in the SV file, go to MonDKP_Meta_Remote table and delete it (this table logs the highest entry other guildies tell you they have during a sync). Then when you see that pop up, it means someone online has old information and needs to wipe.

**Comment by nomenclad** [comment]
I'm not Pewed. I thought that basic users in the guild would auto-sync and that Pewed entry would be removed. The only two people with Officer permissions have the correct .lua. The meta table is there, but if I delete it it is just re-entered when I begin the sync with the guild again. I'll push everyone to get v2.0.6 to try and mitigate it. I've also asked everyone in guild to wipe tables and sync with us.

[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3952085/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
I'm a bit confused. There's only 2 locations within the SV file that tooltip pulls the "missing entries" part from. The Errant table and subtracting an officers entry in the remote table from the same officer within the Meta table. Pewed isn't located in any of those tables. There aren't even any entries indexed by him. But your tooltip said you're missing 25 entries from him?

**Comment by nomenclad** [comment]
I honestly have no idea what's happening. I'll check it again today to see if it still says those entries are missing. We've wiped and sync'd all the officers to have the matching data except Pewed, so maybe when he's wiped and sync'd it will clear itself? I'm also at a loss as to why it says he has missing entries.

**Comment by Roeshambo** [comment]
Is pewed an officer?

**Comment by Roeshambo** [comment]
If he's not then that's most likely the issue. All players report what they have, and if you don't have it, you mark it as missing. The next update is going to be far more stringent on that information so it'll sort that stuff out automatically. But that might not be ready for a few more days.
