### ISSUE TITLE
Issue after Migration

### ISSUE THREAD

**Issue by Arsomang** [Roeshambo/MonolithDKP#212]
We updated to 2.0.5 on Monday and did a successful Migration. Then on Tues on of the officers that wasnt around for awhile logged on with the new update and his addons froze and he reloaded UI and then it forced a migration from him well we were in the middle of a raid. Now no matter what we do even though we rolled back to a save before that happened it keeps saying missing entries from that officer and that everyone is out of date till he sync. If he syncs the dkp everyone had on his table gets added to the dkp they already had on the new table. It seems to be pulling info from just guildies that have the mod also that are not officers. Any help with are tables would be great thanks.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3953352/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
We can definitely get that fixed. The main problem is that everyone must wipe their tables. That's what was pointing to the missing DKP. They thought you still had the data you had when his mixed. So after you remigrated a backup, you had far less entries. And everyone else had far more. So have everyone in your guild wipe their tables. And when I get this remigrated for you, don't do anything with it. Set up a time when all of your officers can meet up together and you'll give each of them this file. So when you all log in, you're certain no one has stray indexes that they send you. You'll probably still see the out of date indicator because non-officer guildies will still be claiming far more entries. But that will clear up as they wipe their tables and download the new ones from you.

**Comment by Arsomang** [comment]
Do we need to have the guild delete there .lua from SV? or just the officers and have the officers add the file you are updating.  Cause if the whole guild needs to delete that how do i know that everyone did it correctly when we have like 100 plus raiders and 700 members how do i know who is using the mode cant guarantee they all see my message.

**Comment by Roeshambo** [comment]
The officers are the most important part. Everyone else will have to wipe their tables. But non-officers can't broadcast. So you'll see an "out of date" status indicator for a bit until everyone gets wiped. But your data will still be good. It'll eventually sort itself out as people get their tables wiped.

**Comment by Arsomang** [comment]
Oh so there tables wipe automatically if there are not an officer?

**Comment by Roeshambo** [comment]
Are these correct DKP values?
![image](https://user-images.githubusercontent.com/6285297/70677126-ddf67000-1c53-11ea-805f-c88b353da8d6.png)

**Comment by Roeshambo** [comment]
No you'll have to tell them to wipe their tables.

**Comment by Arsomang** [comment]
Ok and yes that is correct other then 3 bosses we did after this backup. But we will just have to add them manually.

**Comment by Roeshambo** [comment]
Ok. Good. So like I said, you're still going to see the "missing entries" part. I apologize for that. It will repair over time as people wipe and sync. Whoever has almost 300 entries by "Peu" is likely causing it. 
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3953540/MonolithDKP.zip)
