### ISSUE TITLE
 2 Different Tables - Sync doesnt Work

### ISSUE THREAD

**Issue by Nylinia** [Roeshambo/MonolithDKP#218]
Hey! first of all! We verry Like your Addon! 

But we got some Issues in the past Days.

Me, Nylinia  (Ingame) Officer of our guild are the Only one who changes Things and DKP in your Addon. But after i Updated to 2.0.4 i couldnt Migrate anymore, so i asked another Officer to click on "Migrate", so he Did. After All we got Different Tables and wasnt able to Use your Addon anymore.
So we dediced to Just Delete Everything. All officers Deleted MonDKP+Saved variables. 
So that we can Start up a new Table.

After all i created a new Table, added everyone again and gave them their correct DKP again (Dkp History.html file) but after a few Hours it Synct again with any Officer and we Got Old and corrupted Tables again.. 

So i deleted everything again again and over again.. i`m so tired of this... but nothing was working.. not even a Bit.. Everytime My officers and members got different Tables.. Tripple DKP.

The only one who has the CORRECT DKP Table now, is me! and i tryt to sync it with my Officers after they Deleted their files.. But they get the old corrupted table over and over again. 

here is my Saved Variables from the correct one i using At the moment. (Works for me.. but for no other one) 

[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3962709/MonolithDKP.lua.txt)
[MonolithDKP.lua.bak.txt](https://github.com/Roeshambo/MonolithDKP/files/3962710/MonolithDKP.lua.bak.txt)

it would be nice if u can Migrate it to me (Nylinia-Transcendence) (EU) 

Thanks for your Help and Sorry for my verry Bad english! i hope u got what i wanted to say :)

i'm using 2.0.6 Now. just to let u know

I'm not the Leader of our Guild. Just an Officer.

Do i need to replace anything in our Notes?

**Comment by Nylinia** [comment]
i'm using 2.0.6 Now. just to let u know

**Comment by Roeshambo** [comment]
Nothing in the notes needs to change. You simply have to have all officers/GM delete all of their data (deleting their saved variables file while the client is closed is the most complete way to do so). Best to set up a time for all to do it at once to ensure no officer logs in and rebroadcasts the bad data to another officer. Then they can simply get this data from you or whoever you give the file to. You can also give the file to each officer so they don't have to sync. Everyone else in the guild will need to wipe and get the new data but they can't broadcast so they aren't high priority and won't contaminate your data. You will very likely get a "Missing Entries" notification on your status indicator saying you're out of data. If that happens, it's because someone in the guild had old data and simply told you the data exists as far as they know. It doesn't mean you're actually missing anything. This will be corrected in the next version as I'm putting in several strict filters to help ensure bad data isn't propagated. I'll get your data taken care of as soon as I get home.

**Comment by Nylinia** [comment]
okay, i`ll wait for your respond then :) Thank u!

**Comment by Roeshambo** [comment]
Which one of those files is the correct one? You posted 2 different SV files. Just want to make sure I get your data as accurate as possible.

**Comment by Nylinia** [comment]
I edited my First post and replaced the Saved variables files with the correct Name. 
. both of them are in my Saved Variables.. so.. i really dont know which one is the "correct one" to be honest

The file  MonolithDKP.lua.bak  "last update 12.12 09:29 PM"
and  MonolithDKP.lua  "last update 12.12 09:36 PM"
maybe it helps


Maybe this one will help to find out (From our last raid) 
[dkp-Beute_Stand_History_11.12.txt](https://github.com/Roeshambo/MonolithDKP/files/3961853/dkp-Beute_Stand_History_11.12.txt)
replace .txt with .html

MY Table is correct! everyone has the correct DKP.

**Comment by Nylinia** [comment]
Any Update?

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. Please use 1.6.3 for the time being. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.
