### ISSUE TITLE
A lot of values out of sync after the update

### ISSUE THREAD

**Issue by Jordyderuijter** [Roeshambo/MonolithDKP#219]
Hi there! Im the officer of our guild and yesterday I migrated my addon to the latest version and everything seemed like it was fine after that time. Now when we started raiding our guild leader seemed to have different values than I did. Not only for the current DKP table but also for dkp history and loot tables. This did lead to people not being able to bit the amount of DKP that they 
actually had for example.

Besides that, when I try to edit a certain item on the loot history, sometimes the popup also shows another item than the item I right clicked to edit.

Btw im also a software developer so If you could let me know how to fix the file thats also fine for me.

Here is my lua file:

 
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3957415/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
Not a problem. As soon as I get home I'll get it rebuilt for you. I've got a custom script I wrote that remigrates and removes duplicated data. And am working on a way to incorporate it into the addon for GMs to use (hardest part is writing something that prompts the guild to wipe before they contaminate the newly repaired file). But hopefully all issues will be resolved soonish.

**Comment by Jordyderuijter** [comment]
Cheers mate!

**Comment by Roeshambo** [comment]
Does this look correct?
![image](https://user-images.githubusercontent.com/6285297/70759799-2c1b7a00-1d0d-11ea-93b6-a11e7a104d8d.png)

**Comment by Roeshambo** [comment]
If so, here's the file. There were some corrections made when validating the history/dkp.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3958395/MonolithDKP.zip)

**Comment by Jordyderuijter** [comment]
Hey there, I just did a quick check but the values don't seem to be correct. I think a few items are still missing in the loot history. For example the record of Brutality Blade is missing, which went to Tsordike. Krushak is also meant to be the highest on DKP. See below for the overview shown currently by the addon.
![Capture](https://user-images.githubusercontent.com/3405911/70833771-e3d98600-1df8-11ea-980e-e852f4b5e7e4.PNG)

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. Please use 1.6.3 for the time being. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.

**Comment by Jordyderuijter** [comment]
Fair enough thanks for the update
