### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by shrenk090** [Roeshambo/MonolithDKP#220]
Hello again,

Yesterday you changed the list and I made the thing with the officers.
Today we had the Problem that just 1 officer got an actual list and the other lists haven't updated.
Uploaded the list of the actual migrated officer list after the raid today.
The name of the officer is Aldebaran.
Hope you can Help again with explanations :/

[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3958025/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
Did those officers that didn't update wipe their tables before you deployed the migration i gave you? It's extremely important you have all officers wipe their tables (via the button in options or simply deleting their WTF file with the game client closed) before logging in with the migrated list. Otherwise they'll just send you old data.

**Comment by shrenk090** [comment]
They replaced the old list with the new list yes an logged in again.

**Comment by Roeshambo** [comment]
Ok. So it looks like your indexing is all correct. But there are non indexed entries after that from earlier today (for me at least). What that means is one of the officers were doing DKP with 1.6 which is not compatible. That's likely why they weren't sent to you. Is that what your issue is? All your DKP is correct but you didn't receive any of the entries created earlier?

**Comment by shrenk090** [comment]
Hello,
The officer updated the addon to latest version before he took the list you updated before. He is the only one who gives DKP etc. so there was no 1.6 version running from an officer? The sync I got was that one of the other officer also with version 2.0.6 installed. I don't know whats the problem. :/

Also if I delete everything in my WTF folder and reinstall the addon or wipe the list in option I do not get the sync of him.

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. Please use 1.6.3 for the time being. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.
