### ISSUE TITLE
migration failed please help when you get the chance this is for ponce-rattlegore server

### ISSUE THREAD

**Issue by losthope801** [Roeshambo/MonolithDKP#223]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3958889/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
Make sure all officers delete their saved variables files before their next login. If an officer accidentally logs in with the old data while an officer that wiped their tables is on they'll just broadcast that data back to the officer.

**Comment by Roeshambo** [comment]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3959025/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. Please use 1.6.3 for the time being. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.

**Comment by losthope801** [comment]
thank you for your time hope this works out liking your addon can you link
me to the 1.6.3 Version ?

**Comment by Roeshambo** [comment]
https://www.curseforge.com/wow/addons/monolith-dkp/files
