### ISSUE TITLE
Multiple officers migrated please help! Harskare-Whitemane

### ISSUE THREAD

**Issue by Harskare** [Roeshambo/MonolithDKP#224]
It looks like some of this dkp got multiplied and some of the more recent stuff didn't? I was wondering if you could help me sort this

[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3959303/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
I'll need your SV file. Located @ WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua

**Comment by Harskare** [comment]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3959464/MonolithDKP.zip)
Let me know if this works, I believe its the correct file

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. Please use 1.6.3 for the time being. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.
