### ISSUE TITLE
migration failed 

### ISSUE THREAD

**Issue by Rathanaell** [Roeshambo/MonolithDKP#225]
My guild seems to be having a problem with getting all our tables to show correctly to our raiders. It works with some officers and doesn't work with others can you check our file? My name is Rathanael the file is from my GM Grubes.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3959392/MonolithDKP.zip)

**Comment by joseorlando20** [comment]
I get this message when input / dkp
"Warning: your DKP Modes settings have changed and can not run until your UI is reloaded. Can we reload to complete that?", I click yes, and the problem remain"

Could you help me?

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. Please use 1.6.3 for the time being. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.

Regarding your issue specifically, delete your saved variables file and pull new data from your officers. It's likely a tainted Meta table.
