### ISSUE TITLE
Can I wipe everything and start fresh?

### ISSUE THREAD

**Issue by Blackfire2x** [Roeshambo/MonolithDKP#226]
We have been having the biggest pain getting this to work. We had 1 officer migrate and we all wiped tables and deleted lua files but for whatever reason we have missing entries from 1 officer. We told him again to wipe his files and delete lua files specifically showing him folder and he did yet still issues. I just want to delete all the data and start from 0. We even demoted all the officers to try and make it so their tables aren't valid. I spent 2 hours. As the GM deleting everything and just putting it back in manually only to log in and it all be gone. Is there any option where just the gm can delete all the entries and start fresh and all the officers have to sync to him?

**Comment by charaspepe** [comment]
To add to this:

The GM is Blackfire and the officer who did the migration (Me) is Rikashi. We posted previously and had the table fixed. But we've been unable to get this working even since then.

Are we able to strip any officers out of this table and try it again? We do not have the officer/guild note anymore. Is there a way to re-add this note so the addon force syncs off one of us?

https://github.com/Roeshambo/MonolithDKP/files/3945127/MonolithDKP.zip This was our fixed table from a few days ago. 

Thank you,

**Comment by charaspepe** [comment]
So far demoting officers and deleting all of their monolithdkp.lua from savedvariables doesnt seem to work

**Comment by joheri85** [comment]
i did that when trying to reset and it turns out everyone had to delete monolithDKP.lua.bak also. Otherwise it would just read from that instead. 
But maybe you did that?  only saying since you only mentioned monolithDKP.lua in the last post above.

**Comment by Blackfire2x** [comment]
Yes we all deleted both files. Still no luck

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. Please use 1.6.3 for the time being. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.
