### ISSUE TITLE
DKP tables suddenly broken!

### ISSUE THREAD

**Issue by Sauvig** [Roeshambo/MonolithDKP#228]
Hi Roeshambo

Love Monolith, amazing DKP addon.

However - we have been having sync problems with our tables and then this morning one of my officers logged and it totally skewed the tables. The addon then asked me to validate tables and this further skewed them.

Sequence of events:
1. Originally migrated when 2.0 was released
2. Rolled back to 1.6 - all was fine, addon continued working
3. Updated to new version again and performed migration - all fine at this point too.
4. Downloaded 2.0.6 and sync stopped working - my tables were still correct though.
5. Officer logged on using our bank account - sync auto initiated and 'corrected' my tables, turning the sync to 'red' and saying I had 23 missing options. This is when tables originally got skewed.
6. Addon asked me to validate tables so I did - this caused major differences.

Attached is current LUA file - I can attach the one pre-migration is that is also helpful.

Google sheets shows my CSV export with latest correct figure: https://docs.google.com/spreadsheets/d/1gaE9kpOzQ197z5V4H_HmMXV2rJyEiv1xHmiVIs-lc-k/edit?usp=sharing

Thank you!

Sauv

[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3961360/MonolithDKP.zip)

**Comment by Sauvig** [comment]
Hi there

Saw the rollback notification on twitch today so went back to 1.6.3

The addon won't load with our pre-migration lua, so stuck with current lua.

It opens but amounts are still incorrect.

Thanks

Sauv <3

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. Please use 1.6.3 for the time being. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.
