### ISSUE TITLE
Missing entries

### ISSUE THREAD

**Issue by DthSkeram** [Roeshambo/MonolithDKP#229]
Dth-Skeram Magic and Melee Officer

We migrated over to 2.0.6 on Wednesday and it seemed to work fine. Supposedly all the officers deleted their tables and such and it all worked great that first night. I was the only person who did any loot or DKP changes. The following day I noticed the red button and it says Missing Entries: Dth 11. Not sure what is wrong or needs to be done, but was hoping to find out.

Side note: thanks for all you do on this project. I worked on the WebDKP team a long time ago if you ever used that addon back in wrath/cata and i know how rough it can be with all the requests and issues!
![MissingEntries](https://user-images.githubusercontent.com/58855585/70810500-e48b0180-1d91-11ea-9328-992550691bdb.png)

**Comment by DthSkeram** [comment]
Going to go ahead and upload my SavedVariables .
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3961876/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.
