### ISSUE TITLE
Question: How to contribute?

### ISSUE THREAD

**Issue by BreakBB** [Roeshambo/MonolithDKP#233]
I would like to contribute to this addon and don't know if this repository is updated enough to always be up to date. Any guidelines or explanations would be very helpful!

**Comment by Roeshambo** [comment]
This repository is updated with the latest version in development as features are functional (I won't upload to the repository if something I'm working on is half done). The current version on here should not be considered up to date, however. It is being rewritten at the moment to essentially be 2.0 but with a beefed up version of the 1.6 broadcast system since the 2.0 broadcast system has been causing a bit of heartache. I will hopefully have a functional copy of 2.1 up here within a few days.

**Comment by BreakBB** [comment]
Thanks for you fast response. I will wait then and hope the rewriting is making good progress 👍 As long as you're comfortable with me looking into the code to submit PRs.

**Comment by DanSheps** [comment]
> This repository is updated with the latest version in development as features are functional (I won't upload to the repository if something I'm working on is half done). The current version on here should not be considered up to date, however. It is being rewritten at the moment to essentially be 2.0 but with a beefed up version of the 1.6 broadcast system since the 2.0 broadcast system has been causing a bit of heartache. I will hopefully have a functional copy of 2.1 up here within a few days.

Hey, I know I reached out to you privately on Discord regarding this, but if you would like help setting this up in a more structured way so people can do PR's and such, let me know and I would be more then happy to help.
