### ISSUE TITLE
Inactive data

### ISSUE THREAD

**Issue by AlvinBurunduk** [Roeshambo/MonolithDKP#242]
Hello! My clan members see not relevant table data. How can I fix this? Thanks in advance for your reply.

**Comment by Roeshambo** [comment]
Did you update to 2.1 or are you using 2.0?

**Comment by AlvinBurunduk** [comment]
2.0.6

**Comment by AlvinBurunduk** [comment]
In the application, Twitch is only 2.0.6. I’m from Russia, can it somehow affect?

**Comment by Roeshambo** [comment]
Nope. 2.1 is posted as a beta so it's not forced on anyone because 2.1 is not compatible with 2.0. It reverts back to the old broadcast system as some are having issues with the 2.0 version. With 2.0, if a player is deleted from the list, it should broadcast that list to other players unless another officer readded them.

**Comment by AlvinBurunduk** [comment]
you mean that i should go for 2.1?

**Comment by Roeshambo** [comment]
2.1 is far more reliable than 2.0 with regards to broadcasting. The sync system had some quirks in it and if an issue arose it tended to just compound on itself due to automatic propagation. 2.1 essentially uses the 1.6 broadcast system with a UI to choose who to send it to rather than simply broadcasting to everyone. But 2.1 is not compatible with 2.0. So if you use 2.1, everyone else must as well.

**Comment by AlvinBurunduk** [comment]
where can i dowload 2.1?

**Comment by Roeshambo** [comment]
It's available on Curse. I posted it as "beta" so the twitch client wouldn't auto install it for some when today is raid resets. 2.1 doesn't work with 2.0 so if some auto downloaded 2.1 and their raid leaders were still on 2.0 it they wouldn't have been able to participate.

**Comment by AlvinBurunduk** [comment]
but my clan members have 2.0 and I have

**Comment by Roeshambo** [comment]
If 2.0 works well for you you can stay with that. The sync project was abandoned though due to several data retention issues. So all further updates will be off of 2.1

**Comment by AlvinBurunduk** [comment]
Thanks, got it! Good luck and thanks for the addon
