### ISSUE TITLE
downgrade to 1.6.3 intentional?

### ISSUE THREAD

**Issue by Djfe** [Roeshambo/MonolithDKP#245]
is it intentional that everyone just got downgraded to 1.6.3 again (by twitch)?
2.1.0 is still in beta.

**Comment by Roeshambo** [comment]
2.0 was having some major issues. I could have fixed them (and almost did). However, the sync system as a whole was relatively taxing and was causing lag for those that were on lower end machines. So ultimately I decided it was better to just scrap it as it was rather ambitious to start with. 2.1.0 is basically 2.0 but with the 1.6 broadcast setup (with some added features). And I only posted it as beta because it was posted Monday night and I didn't want people using the Twitch client to automatically install 2.1 the day of raids when their guild would likely still be using 1.6 or 2.0 (2.1 is not compatible with older versions as it uses different compression/encoding as well as a different algorithm for handling incoming broadcasts.

**Comment by Djfe** [comment]
thanks for explaining the issues with 2.0.x
So what you are saying is:
2.1.0 is actually a release and we can upgrade and don't have to expect problems?
(of course everyone has to upgrade, the thing is: twitch downgraded our 2.0.6 to 1.6.3 instead of updating to 2.1.0, 2.0.6 was deleted from twitch; right now we are on 2.0.6 because we have the zip file still)

**Comment by Roeshambo** [comment]
I was honestly not aware twitch would auto install 1.6.3 if you had 2.0.x when it was removed. I'll be releasing 2.1 as a release shortly. In it's current state, no there should be any issues as there is no automatic broadcasting. But the safest transition is to have the officer with all complete data broadcast the full table to everyone just to make sure everyone's data is identical.

**Comment by Djfe** [comment]
I'm sorry I have to correct myself. The way people told me about it sounded a lot like that was the case.
I actually used twitch's update mechanism now (I avoided it before) and it didn't mess with 2.0.6 (at all)

I guess the only issue was that people who weren't on 2.0.6 couldn't update to that anymore?

The bottom line is everything actually is the way you expected it to be.

Good to know we can update to 2.1.0 safely :)
