### ISSUE TITLE
Guild Leader Note Problems.

### ISSUE THREAD

**Issue by CTekk** [Roeshambo/MonolithDKP#31]
I don't know if it's a real Issue or more of a Question if it can be implemented. The Problem is that our guild Save information in the Guild Note for the officers. Also, not every officer that can see and edit the Guild Not are a Raid Officer so that's a no go for us. I like the addon but is there an option to only save it local ? And Player can whisper the Raid Lead how much points they have ?

**Comment by Roeshambo** [comment]
There is no current option for a local only version of the addon. But if i get some free time I can look into adding that as an option.

**Comment by Arsonal** [comment]
I didn't wanna start a new issue since ours is similar. Our guild likes to use personal notes for fun and setting profession and stuff. Keeping the timestamp either in the savedvariables or officer note is more advantageous. 

On that note, on your wowinterface page at the bottom it states setting the personal note timestamp to 0 and rebroadcasting will update everyone back to the correct status, I want to verify this correct?
We broadcast before and after raid so this should bypass the need for the timestamp, no?


Also to answer @CTekk question on whispering dkp, its in the /dkp help use !dkp <player_name>

**Comment by Roeshambo** [comment]
The time stamp is kept on the guild leaders public note. That's the only note that is changed. No other notes are effected in any way. As far as keeping the time stamp in the saved variables file, it is. The public note is to verify to each user if they have the most recent tables and to prohibit officers from broadcasting out of date tables. Imagine logging in and an officer that missed the last raid broadcasts his tables because he was unaware it's out of date, and now all your data is gone and cant be recovered.
