### ISSUE TITLE
increase the time until the timer ends if there is a new bid

### ISSUE THREAD

**Issue by Gamelander** [Roeshambo/MonolithDKP#32]
Now we have small abuse, Players waiting untill timer almost tnd and bid, Last max bid won.
Need to increase the time until the timer ends if there is a new bid, fo eaxample for 10 seconds or optional time after last bidding.

**Comment by Roeshambo** [comment]
None of the data in the bid window is cleared until the item is awarded. The easiest way to rectify this is to change the timer in the bid window after the bidding is completed if a player attempts to snipe to something like 10 or 15 seconds, and simply start the bidding again. It will retain bids from the previous bid session. I may add an anti sniping feature to it but it'll be something I'll have to work my way towards since there is an effective work around.
