### ISSUE TITLE
Where is the guild's data stored?

### ISSUE THREAD

**Issue by druryguide** [Roeshambo/MonolithDKP#37]
I would like to know where is the data stored so that I can make backups.

**Comment by Roeshambo** [comment]
The information provided in the readme here, as well as at WoWInterface and CurseForge provides that info.

"- Due to the volatile nature of WoW Addons and saved variables, it's recommended you back up your SavedVariables file located at "WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua" at the end of every raid week to ensure all data isn't lost due to somehow losing your WTF folder."
