### ISSUE TITLE
Problem with updated tables

### ISSUE THREAD

**Issue by Bjadke2p** [Roeshambo/MonolithDKP#46]
Hi,

I ran into a problem while updating the loot tables. 
It seems like we no up to date officer tables.

![InkedWoWScrnShot_101619_231347_LI](https://user-images.githubusercontent.com/56656512/66959574-f179c600-f06a-11e9-8e43-fdf5da8c2a0a.jpg)

I think the problem is multiple people editing at the same time. I have already asked all the Officers, if any of them had the green light in the left bottom corner but all are red. Any idea how to fix this?

**Comment by Roeshambo** [comment]
The time stamp can be deleted from the guild leaders public note to reset that. But once you do, make sure you have one person that has all up-to-date data to broadcast to everyone so you know everyone has the correct data. Multiple people doing updates at once could cause something to go out of sync since broadcasts happen over time. They're not instant. Broadcasts happen over chat and abide by the same rules as chat. Only X length messages can be sent every Y seconds or it will disconnect you for flooding. So the longer your tables are, the longer it takes to broadcast (I tested a loot history log with about 1,000 entries and it took almost 3 minutes to send the entire thing). If you have multiple people doing it at once, they can get mixed.
