### ISSUE TITLE
Bugs encountered in first raid

### ISSUE THREAD

**Issue by rpiwetz** [Roeshambo/MonolithDKP#56]
1. We had the interval set to 20 with bonus of 5, but the tool never awarded those points.
2. When I ended the raid, 20 points were awarded, but the log shows that 10 were awarded instead, so now most of my raiders have points that don't add up based on what is in the DKP history.  Anyone who received end of raid bonus received the extra 10 points.

**Comment by Roeshambo** [comment]
The timer doesn't award points if you're in combat. Instead it checks every 30 seconds to do so out of combat. Were you chain pulling by chance? As far as the history, when DKP is awarded it uses the same variable to fill the history entry. What does the DKP History entry say for reason? The timer may need to be lowered to account for quick pulling.

**Comment by rpiwetz** [comment]
We were out of combat quite a bit...not chain pulling.  For the players with 35 points, they all have 2 entries...15 points for on time bonus, and 10 points for end of raid bonus.
I neglected to mention that we were using the latest version (1.5.3 i think) for this raid.

**Comment by Roeshambo** [comment]
Were you the raid leader? If not, does the raid leader have the addon? The start and end raid distributions are done by the player that pushes the initiate and end button. But since the timer is broadcasted to all officers to start, the interval distribution is only done by the raid leader. So the raid leader must be an officer and have the addon to distribute the points. Otherwise all officers would attempt to distribute them (if you have 4 officers in the raid, all 4 officers would apply the interval bonus resulting in .. well.. too many points being handed out). This also allows the raid leader to pass lead to another officer if they were to get DCd or reloaded and lost the timer so distribution still occurs on time.

**Comment by rpiwetz** [comment]
That most likely explains it...i started off RL but passed it once we got going.  The extra 10 points are probably from the end of the raid when i became raid leader again, before ending the raid.  Sounds like the time based points don't show up in the log anywhere?  I guess that makes sense since it would create 3 entries per hour in my case.  Still causes confusion since the DKP history won't match up to people's points.

**Comment by Roeshambo** [comment]
It should match up with peoples points. Unless it wasn't broadcasted properly. And yes, whoever hits the start and end button distributes the the start and end raid bonuses. Time based entries show up in the log, but if the leader of the raid doesn't have the addon with a timer running, it simply doesn't distribute the points. It's programmed to only give points if you are the raid leader. As far as the history matching up, I'm working on a brand new system to make sure no data is lost.

**Comment by rpiwetz** [comment]
Thank you for taking the time to respond, and to make such a great addon!

**Comment by rpiwetz** [comment]
Last week's raid was experiencing the same issue of Raid Intervals not awarding points.  I was Raid Leader the whole time, after Initializing the raid, the timer was counting up, but no time based points were ever awarded.

**Comment by Roeshambo** [comment]
We're you in combat when it ticked over the interval? And what version were you using? Also what Interval and Bonus do you have set

**Comment by rpiwetz** [comment]
I had it set to 20 minutes, 5 bonus points.  Version 1.5.4
I doubt we were in combat every 20 minutes during the 6 hours we raided.

**Comment by Roeshambo** [comment]
I sincerely can't answer this. Though I'm on 1.6.2 (plus a few developing additions) and it's working perfectly for me with every variation of the timer options I can set. But I haven't done too much with the raid timers since I added the resync. Did it work prior to 1.5.4? I did identify an issue with the sync broadcast that I fixed, but it didn't impact the actual timer. Just the broadcast of the settings to be auto applied for other officers.

**Comment by Roeshambo** [comment]
Replace these 3 files in your MonolithDKP\Modules folder and let me know if it fixes your problem.

[Modules.zip](https://github.com/Roeshambo/MonolithDKP/files/3781458/Modules.zip)

**Comment by rpiwetz** [comment]
None of the versions have awarded time based points (I think we started at 1.5.2).  I tried the files you had linked previously, and got excited when my test raid started adding points (every 1 minute for testing).  But then i removed the patch files and it was still working...
I am normally Raid Leader, Master Looter, and set as Main Tank, so I set all those in my test raid, and it still worked...
From looking at the code, I see how you check Raid Leader to see whether to be applying points...is there a way for me to call that function manually from within game (a console?) to verify that it is returning true next real raid?
I'm a programmer, but new to lua and wow addons, but willing to help in any way to track this bug down.
Thank you.

**Comment by Roeshambo** [comment]
You can run any Lua code by preceding it with /script. So if you have 2 people in your raid you could do:

> /script for i=1, 2 do local name,rank=GetRaidRosterInfo(i); print(name, rank) end

to print each raid members name and rank. Leader = 2, assist = 1, none = 0

**Comment by rpiwetz** [comment]
Finally able to raid again tonight...i disable other addons and points were awarded as expected.  Thanks again!!
