### ISSUE TITLE
Bidding automatic min-bid increase 

### ISSUE THREAD

**Issue by perara** [Roeshambo/MonolithDKP#62]
Would it be possible to add functionality to enable users to bid via a simple
!bid
Where the bid would be "current max bid" + a "minimum bid increase" .

in the case where someone bids and does not have that amount of dkp it would simply be rejected.

**Comment by perara** [comment]
To make this abit more clear
The Officer/Raid leader sets min-bid to 2
min_bid = 2
start_bid = 1

Player 1: !bid    -> Bid is 1
Player 2: !bid    -> Bid is 3
Player 1: !bid 8 -> Bid is 8
Player 2: !bid     -> Bid is 10

Etc :)

**Comment by Roeshambo** [comment]
I'm considering a user interface for the remainder of the raid. But it might be some time.

**Comment by perara** [comment]
Could you please advise me on how to do testing with the application?
I could implement such a feature, but I did not find any clear way of running the addon in "test mode"

**Comment by Roeshambo** [comment]
Only way to really "test" it is to use it in with it's intended functionality. I've been simply keeping a backup savedvariables file for my current guild, do testing as needed and then restore the backup and change the GM note back to the appropriate time stamp. I've also been using two accounts on the retail server (so I can actually do molten core and BWL etc solo) and testing it there. Though there are a few minor things that don't function on the live server properly as the element simply doesn't exist (such as when you query the guild for talent specs since talent builds don't actually exist in retail.. etc) so they error out. You just have to be aware of that so you know what errors matter and which ones can be overlooked.

**Comment by perara** [comment]
@Roeshambo 
Seems like this is something quite a few people would like. I made a little addon based on the chat messages MonolithDKP outputs. Works "OK" but would work significantly better to embed this into the Monolith ecosystem
https://www.curseforge.com/wow/addons/monolith-dkp-bidframe

**Comment by Roeshambo** [comment]
2.0.2 beta has a comprehensive bidding UI built in for other players.

**Comment by perara** [comment]
Perfect!
I will be removing the addon as soon as its released!

Good job!
