### ISSUE TITLE
Guild Leader Updated, and reset DKP to a few weeks ago

### ISSUE THREAD

**Issue by Mayhemfury** [Roeshambo/MonolithDKP#74]
I am a co GM, and Raid leader for my guild. we sue Monolith DKP and i am the one who leads the raids and updates all the DKP. My GM has not raided in a couple of weeks, he logged in and updated the addon with the twitch client. when everyone else logged in and updated the addon had erased everyones DKP back to 2 weeks ago when he raided and we have no record of the DKP earned / used in the last 2-3 weeks. this is causing a huge fuss in the guild. how can we fix this, and how can we stop this from happeneing again??? please help.

**Comment by Roeshambo** [comment]
In your WTF\Account\ACCOUNT_NAME\SavedVariables folder, there are 2 files. MonolithDKP.lua and MonolithDKP.lua.bak. The bak is a backup of how the file was, but only for one relog. You can deleted the lua file and then remove .bak from the backup. Beyond that, there's nothing else that can really be done aside from hope someone had a backup. I mentioned several steps that could be taken to prevent that from happening on curse/wowI because the wow API is volatile. One of the easier methods is after each raid you do a /reload to commit the new data and then save a copy of the savedvariables file into a private discord channel for your officers with a brief description of when/what raid it's backed up until. I'm currently working on a new broadcast system that should help guarantee data integrity when it comes to broadcasting. But it's still in development. I'm hoping to get it rolled out as soon as possible. But for now, i would recommend you tell your officers not to ever use the broadcast button unless they know what they're doing. And secondly, if an out of date broadcast was pushed, you should have received a confirmation to allow it to save.

**Comment by Mayhemfury** [comment]
Okay thank you I’ll give that a try. I am not the GM so would I have still
received that prompt to allow it to save? So the values will only adjust if
someone broadcasts? Just trying to get this figured out so our GM doesn’t
accidentally screw it up again.

**Comment by Roeshambo** [comment]
If their tables are out of date any broadcast they manually push should have alerted you that it was out of date. Only someone with current tables should try to broadcast. If they are out of date, someone that is up to date should broadcast to them so they are on the same page. The new broadcast system should correct this entirely.

**Comment by Mayhemfury** [comment]
Okay awesome. I’ll make sure to save after every raid and only have myself
broadcast. Thanks man and thanks for an amazing addon.

**Comment by Roeshambo** [comment]
It's just a good idea to back up the data because of silly reasons. I even do a manual /reload after I distribute loot after every kill. Because if you disconnect, any new data since you logged in is lost. Doing a reload commits that data to the file so it doesn't get lost. The API is just very poor with data retention. The new broadcast system will query the guild for any individual entries you're missing automatically.

**Comment by Mayhemfury** [comment]
Okay thanks man. Is there any way to reverse a decay? Or no?

**Comment by Roeshambo** [comment]
Yes, you can right click it and delete it in the DKP history like any other. However, for it to be precise, it needs to be done before any other edits are made. So if you do a 20% decay, and then award everyone 10dkp, for example, when you delete the 20% it will not give them exactly the same amount as was deducted.
