### ISSUE TITLE
Options Available

### ISSUE THREAD

**Issue by ZachHandley** [Roeshambo/MonolithDKP#80]
Hi!

We love the addon and it's incredible. I have a few things I wanted to know if they could either be set or something else

1. WoW Servers disconnect sometimes (especially with CoD launch), is it possible to keep the raid timer going through multiple people's DKP? Maybe Officers?

2. Is it possible to do a bidding style where when someone bids the highest bid it resets the timer and announces the bid? Like 10 seconds then first bid resets it to 10 seconds and announces it, second timer starts and then people can keep bidding?

3. Can we Alt + Shift click to bid an item from inventory? It would require US to know that it's tradable but just curious

Thanks again for the addon, if none of these work it's all good :)

- Zach

**Comment by Roeshambo** [comment]
1. When you start a raid timer, it's broadcasted to all officers within the raid. They will all have the same timer running in the window as you. Every minute, they will also rebroadcast that timer to sync up anyone that is either new, or had their UI reset from a disconnect or /reload.

2. It's already implemented into the newest version but hasn't been released yet as I'm waiting on a few other things to be finished (it will require everyone in the raid have the same version or later and I'd rather get it all into one rather than require everyone update multiple times). It'll be an Anti Snipe feature in the dkp modes window and lets you choose how many seconds to add to the timer if someone bids below 10 seconds remaining.

3. You can not as that would require a rewrite of the script for every possible bag addon that people are using. You can, however, use the /dkp bid [item_link] command to do the same thing. 

The dev version on this Git does include all of the updated features. But will require everyone in the raid be updated to this version to use it properly. Go [here](https://github.com/Roeshambo/MonolithDKP/commit/08d53eca5986f9c83b12a399d120cbf21bf4940c) to see the newest additions.
